### ISSUE TITLE
Complete draft Standards Documentation Standard

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#1]
This document would be focused on the formatting of human and machine-readable documents used to describe standards.  It would replace the current draft standard http://www.tdwg.org/standards/147/

**Comment by peterdesmet** [comment]
I'm in the process of moving the TDWG standards to GitHub. This has already been done for prior standards and dwc. Regarding http://www.tdwg.org/standards/147/:
1. To which repo should that content (cover page + download) be moved to? A new repo or this one (e.g. subfolder)?
2. Is there a need to actually keep that content somewhere?
3. Is the URL http://www.tdwg.org/standards/147/ in use? Where should it be redirected to?

**Comment by baskaufs** [comment]
On the old TDWG website, the URIs for standards were called "permanent URL"s.  They were applied to draft standards as well as ratified standards.  So I think they should continue to dereference to somewhere indefinitely, even if a draft standard is abandoned.  If this group's task is to replace that draft standard, then I suppose it might make sense to have that URI redirect to a landing page for the Vocab Management Group, and then link to the old content for historical purposes.  

Eventually the Vocab group will have a web page on the "new" TDWG website, but that hasn't happened yet, so I think having the redirect go to the GitHub landing page for the group (https://github.com/tdwg/vocab) would make sense, given that a purpose of the GitHub repository is to make sure that content is archived.  That landing page could contain a link to the content related to the abandoned draft standard (i.e. subfolder), but would also inform users that the abandoned draft standard is being replaced.

**Comment by baskaufs** [comment]
~~Blocked on Issue #4~~ Issue #4 is closed

**Comment by baskaufs** [comment]
~~Blocked by Issue #17~~ Issue #17 is closed

**Comment by baskaufs** [comment]
Blocked by Issue #18

**Comment by baskaufs** [comment]
~~Blocked by Issue #20~~ Issue #20 is closed

**Comment by baskaufs** [comment]
A draft is complete and is at https://github.com/tdwg/vocab/blob/master/documentation-specification.md
