### ISSUE TITLE
vocabulary document citations

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/vocab#24]
Important documents about a TDWG-managed vocabulary should always include preferred citations at least in human readable and RIS form and preferably in BibTeX form.  If feasible, these should be in standardized form, perhaps given by some template.

This should apply at least to normative and best-practices documents.

**Comment by baskaufs** [comment]
Added the text "It should also include a preferred citation in human-readable form and provide access to one or more standardized machine-readable citation export formats." to Section 3.2.3.4 (the footer)
