### ISSUE TITLE
Acknowledging contributors to documents and standards

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#37]
The hierarchy model as currently constituted in the draft Documentation Specification is more complicated than what was envisioned in the original draft documentation spec.  How, and at what level, do we acknowledge contributors?  For a standard that contains multiple documents (such as Darwin Core), the contributors are acknowledged at the document level rather than at the standard level, and that seems right.  However, on the level of a vocabulary, particularly an evolving vocabulary, how do we acknowledge the continuing contributions to the development of the vocabulary?  There will ultimately be many contributors, so do we just not worry about that and list only the contributors to the original vocabulary?  Since releases/versions of the vocabulary are tracked as time goes by, do we add names of new significant contributors?  see section 4.2 of the draft

Also, I think that it's a serious omission to not acknowledge the review manager for a standard.  Although the review manager isn't an author, it's a huge job and the review manager does make a significant contribution to the standard.  I think it's somewhat of a parallel to acknowledging the subject/corresponding editors of journal articles.  In this case, the contribution would need to be acknowledged at the standard level.  The current draft of the specification is silent on this.

**Comment by ramorrismorris** [comment]
I concur.  For Audubon Core, it is arguable that the review manager invested more time than any single one of the authors, at least in the 12 months leading to adoption.  I even believe that the exchange between authors and reviewers and those between authors and review manager should be part of the public, permanent record.

**Comment by baskaufs** [comment]
From an email: 
We didn't discuss this issue in the call. However, I'm

> thinking that it may be out of scope to specify in the documentation
> specification who should be acknowledged as contributors. The purpose of
> the spec is to say how contributors should be acknowledged, but deciding
> who should be acknowledged is really a policy decision that doesn't have to
> be written into a standard.

John W. concurred with this and there was no dissent, so I'm going to close the issue.
