### ISSUE TITLE
How is the normative part of a standard designated?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#4]
In the draft standards documentation standard, particular documents are designated as "Type 1" = normative.  In some non-TDWG standards, sections within the same document can be designated as normative or non-normative.

**Comment by baskaufs** [comment]
Blocked on Issue #5

**Comment by ramorrismorris** [comment]
W3 Recommendations do it with designated sections within the document, and that seems to work well. However, part of that is because the Recommendation is always a web document and always contains easy to find labels signifying whether a section is normative or not.

**Comment by xjsachs** [comment]
I support eliminating the “Type” designation of documents, and designating normative parts of documents with text in the document itself (as per https://docs.google.com/document/d/1GEDlVAHpvFj4RuiwATSy5oIxz5JpgBC84yDyGrZvEB0/edit).

**Comment by baskaufs** [comment]
At the TG meeting of 2015-07-15, there was general agreement that the designation of particular documents as "type 1", etc. should be dropped.  Instead, the standards documents should clearly state which sections are normative and which are non-normative.  Generally the normative description of a vocabulary should be in a human-readable format, although there may be some circumstances where it may be necessary to designate all or parts of some machine-readable documents as normative.
