### ISSUE TITLE
Inconsistent English language tags

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#42]
In the Darwin Core RDF, some documents tag literals using "@en", while others use "@en-US".  Should they all be "@en" or should the variety of the writer be noted?  Does it matter?

**Comment by tucotuco** [comment]
@baskaufs I am not sure what you mean. I can see no references to "en-US" in any of the three RDF documents "dwcterms.rdf","dwctermshistory.rdf", and "terms/guides/rdf/index.htm".

**Comment by baskaufs** [comment]
Sorry, I should have been more specific.  The "en-US" tags are here:
https://github.com/tdwg/dwc/blob/master/terms/attributes/dwcattributes.rdf
which also comes from here:
http://rs.tdwg.org/dwc/terms/attributes/
when you dereference the dwcattributes: terms.  There are also several other problems with dwcattributes.rdf but I should probably raise them on the DwC issues tracker.

**Comment by tucotuco** [comment]
Fixed in c7c38601b996a66f3c1f6cf359d4ae8740bde5a2.

**Comment by baskaufs** [comment]
This was somewhat of a theoretical issue as opposed to a bug report for DwC.  Is it a better practice to tag literals more generically as "en" and not worry about the flavor of English?  I suppose it might matter in the case of term labels, like "license"@en-US vs. "licence"@en-GB, but probably not most of the time.
