### ISSUE TITLE
Term Labels

### ISSUE THREAD

**Issue by tucotuco** [tdwg/vocab#43]
In section 3.3.3.1 it currently says "Label (optional? DwC doesn't list it in the human-readable representation) - The label is a word or short phrase that serves as a human-readable name for the term."

DwC does have the english language label in the Complete History document. I don't feel strongly about whether it should be required, but if it is, should the language attribute be required?

**Comment by tucotuco** [comment]
See also Issue #35 with respect to normative vs. non-normative.

**Comment by ramorrismorris** [comment]
The normative [Audubon Core Structure document ](http://terms.tdwg.org/wiki/Audubon_Core_Structure) carries  this: "Term Names are intended principally for navigation in the AC documentation. Term Labels are suggestions for English labels in applications. They are recommendations only and are offered only in English, with the added expectation that they may clarify intended usage of the term. Communities may wish to promulgate recommendations for Labels in other languages, or even alternative English Labels for specialized audiences, e.g. school children. Labels are may be used for navigation within the Term List, and are often used within the Term List itself when a term is mentioned within the documentation of another term. The Term List provides indices both by name and label. "  This seems like a good practice. Possibly so does use of, or at least friendly to, the [TDWG Terms wiki ](http://terms.tdwg.org/wiki)

**Comment by baskaufs** [comment]
I have been using the [existing unratified documentation spec](https://github.com/tdwg/vocab/blob/master/tdwg-stds-spec.pdf) as a starting point and have departed from it when I thought experience has shown that it doesn't work.  Section 12 says "All normative (Type I) documents must be in English.  Translations of normative documents may be included in the standard but the translations must be treated as informative (Type 2) documents."  Given this as a starting point, I've assumed that all definitions, comments, and labels would be provided in English.  In RDF, best practice indicates that they should be language-tagged.  

My understanding is that there is a desire by groups like GBIF to provide these kinds of human-readable strings in multiple languages.  So the question is how to best accomplish that.  In the existing draft of the spec, I've assumed that non-English labels would be generated outside of the standard (in what we are currently calling "Type 3" documents).  But that was based on the assumption that standards documents would be relatively immutable and changed only by some official process.  But I'm getting the feeling that if we allow documents to consist of normative and non-normative sections, we considering being a lot looser about the non-normative parts.  If we change a non-normative example, does that have to go through some sort of official change process?  

The situation with labels is similar.  If we consider the labels to be included in the standard and add labels for Croatian, or change the French label from one thing to another, can anybody who has write privileges just do it, or do they need to open a term change issue?  What if the translation is of the term definition?  I think we need to talk about this general issue at the Hangout.

**Comment by baskaufs** [comment]
Here is some text from the [2016-05-04 meeting notes](https://github.com/tdwg/vocab/blob/master/meeting-notes/meeting-agenda-notes-2016-05-04.pdf) about this issue:

As described in the comments related to Issue #36 , the text of the draft currently specifies that English-language labels should be provided and that they should be language-tagged in the RDF.  The text about labels in other languages being outside the standard is unchanged from the earlier draft.  There did not seem to be any objection to these specifications so I didn’t change them.  If people have strong feelings about them, it can come up in public comment.
