### ISSUE TITLE
terms by inclusion

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/vocab#44]
It's unclear to me whether this needs addressing in the spec, nor whether it currently impacts anything other than AudubonCore (AC)

The [AC normative term list](http://terms.tdwg.org/wiki/Audubon_Core_Term_List#Geography_Vocabulary) carries "All geography terms from the DarwinCore version of 9 Dec 2009 are deemed included in the Core Layer. Specifically, this includes exactly those which are declared by DarwinCore to be in DarwinCore Class Location"

Perhaps short of  referring to some formal class structure, probably in a serialization, it might be ipso-facto impossible to normatively include the DwC Geography terms in a machine-readable spec, short of including each such term.

**Comment by baskaufs** [comment]
Well, I think that the existing draft of the documentation specificatin has a mechanism dealing with this sort of term "borrowing" via "term lists" (Section 3.3.3 with regards to the human-readable representation, and 4.4 through 4.4.2 with regards to the machine-readable representation).  It would be possible to define the terms that were included in that particular version using some kind of SPIN rule or something, but it seems more straightforward to just enumerate them.  The required triples would be minimal, something like this: 

```
<http://rs.tdwg.org/ac/borrowed/>
     rdfs:label "Audubon Core Borrowed Terms"@en;
     dcterms:isPartOf <http://rs.tdwg.org/ac/>;
     a dcat:Dataset.
<http://rs.tdwg.org/dwc/terms/continent> dcterms:isPartOf <http://rs.tdwg.org/ac/borrowed/>.
<http://rs.tdwg.org/dwc/terms/waterBody> dcterms:isPartOf <http://rs.tdwg.org/ac/borrowed/>.
<http://rs.tdwg.org/dwc/terms/islandGroup> dcterms:isPartOf <http://rs.tdwg.org/ac/borrowed/>.
[etc.]
```

This is similar to the non-authoritative term list example in section 4.4.2.2
