### ISSUE TITLE
Enabling "semantically enhanced" vocabularies through vocabulary extension term lists

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#45]
Previously, the [draft standards documentation specification](https://github.com/tdwg/vocab/blob/master/documentation-specification.md) implied that there was a mechanism for adding "semantic layers" to basic vocabularies without imposing those semantics on the vocabulary for users who weren't interested in those semantics.   This has come up on multiple occasions on TDWG Content - I'm too lazy to look them all up, but here's one: http://lists.tdwg.org/pipermail/tdwg-content/2013-June/003049.html .  However, until now I hadn't actually written any text about how this would be done.

I've fleshed out the way to accomplish this by adding section 4.4.2.2 and including an example at the end of section 4.4.2.3.  You can also get the idea from the diagram at https://github.com/tdwg/vocab/blob/master/hierarchy-model.md, although this diagram is out of date and does not reflect everything that's in the current draft (for example, it uses owl:imports in places where the current draft specifies dcterms:hasPart).  Anyway, the point is that there wouldn't be just one Darwin Core vocabulary.  There would be several depending on how many semantic layers one wishes to place on top of a basic "core" bag of terms.  The same would be true with Audubon Core and any future TDWG vocabularies.

The Turtle illustration in section 4.4.2.3 uses triples I pulled from http://terms.tdwg.org/wiki/Audubon_Core_Term_List_RDF_Version, which has no official standing.  This example actually illustrates the value of the layered approach.  There is not currently ANY RDF representation of Audubon Core because it's never been finished.  In the layered approach, there would always be a basic "bag of terms" RDF representation that is created immediately upon the adoption of terms and based primarily on sticking the human-readable definitions into rdfs:comment values.  The heavier-weight semantic layers could be added later when/if they are ever written and tested.

I'm not blocking the completion of the draft on this issue, because as far as I'm concerned I've completed what I plan to write on this.  However, I've opened this as a separate issue to create a place where people can put comments specifically related to this approach.  I'll revise based on any feedback that is received.

**Comment by tucotuco** [comment]
I agree that there is immense value in separating the layers, and as
needed. In practice it is probably good idea to model the terms in the
context of an ontology in order to try to achieve some rigor about their
meaning, but I wouldn´t proscribe that.

**Comment by baskaufs** [comment]
I'm going to close this issue, since the only comment was positive.

**Comment by jar398** [comment]
I meant to reply but got sidetracked. I think my reply would have been
negative and not helpful, so carry on. I will try to write down my thoughts
about "layered semantics" elsewhere.

**Comment by ghwhitbread** [comment]
I must admit to struggling with this myself Jonathan.  And I've had little
joy in hunting down arguments for the for or against.  Perhaps I have not
been asking the right questions.  If you haven't recorded your thoughts on
layered semantics yet (only a few days I know) can you provide any pointers
to discussions of the rationale for either case?

Greg

On Friday, 24 June 2016, Jonathan A Rees notifications@github.com wrote:

> I meant to reply but got sidetracked. I think my reply would have been
> negative and not helpful, so carry on. I will try to write down my thoughts
> about "layered semantics" elsewhere.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/tdwg/vocab/issues/45#issuecomment-228190581, or mute
> the thread
> https://github.com/notifications/unsubscribe/AFiQ-_mrD4Q2Gh5w3YYMkMvtfxeTGNLJks5qOvtOgaJpZM4Ie20_
> .

## 

Greg Whitbread
+61 418 670 368

taxamatics
