### ISSUE TITLE
Response to expert review

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#47]
I wanted to update the Task Group on the status of the response to the expert review.  I have updated the TG landing page with links to several documents relevant to the review.  Among those documents are a response to the reviews and a change log.  

The response to reviews is a systematic series of responses to each of the issues raised in the reviews.  In some cases, the responses are an explanation of why I did not make an changes in response to that particular issue.  I wrote this on behalf of the TG, and generally used first person plural, so if you are able, please look this over and let me know if there is anything that I have written to which you object.  

The change log is a much briefer listing of the major changes that I made to the documents.  Please look this over carefully and give me feedback if necessary.  

There is still one remaining change that I need to make and that is to simplify the examples.  I believe that the fuller examples do have value as a sort of "template" for how to write the RDF.  However, I also agree that including extraneous information may obfuscate the point of a particular section in the specification.  What I plan to do is to move the more lengthy examples to an appendix, and then within the text hack them down to the bare minimum.  

With respect to shortening and simplifying the human-readable text, I haven't really done anything except to make changes based on reviewer suggestions.  I'll give them another look in the light of shortening and simplifying, but generally what I already had was as simple as I thought it could be and still include the details necessary to conform with the specification.  I would welcome any suggestions for simplifying and shortening the text.

One significant change that I made unilaterally was to mint two new terms:

http://rs.tdwg.org/dwc/dwcattributes/Dataset

and 

http://rs.tdwg.org/dwc/dwcattributes/Vocabulary

My take from the discussion of the RDF TG was that minting new terms that mean exactly what we mean is preferable to co-opting other terms that don't exactly fit our needs.  The unilateral decision I made was to put them in the http://rs.tdwg.org/dwc/dwcattributes/ namespace.  Currently, that namespace is considered to be part of Darwin Core, but I've essentially redefined it to be a TDWG-wide utility namespace, and that is reflected in the "new" namespace abbreviation that I suggested for it (tdwgutility:).  There are existing terms in that namespace, such as http://rs.tdwg.org/dwc/dwcattributes/status and http://rs.tdwg.org/dwc/dwcattributes/decision that should probably be used TDWG-wide, so it made sense to me to broaden the scope of this namespace.  I do not think that it would be beneficial to create or move them to a new namespace just because the URI structure implies that it's a Darwin Core namespace.  There is no point in breaking current implementations by changing the namespace.  Rather, clarify that the namespace applies TDWG-wide by saying so in the metadata associated with http://rs.tdwg.org/dwc/dwcattributes/ .  If you disagree with this change to the draft, please comment here.  

I'm informing you of the situation and asking for feedback now (rather than when I've completely finished the revisions) because the Review Manager (Dag Endresen) would like to get the response from us before the next Executive conference call scheduled to take place around January 24-25.  Getting these revisions done quickly has been difficult for me due to work-related constraints associated with the start of the semester at Vanderbilt.  However, I would prefer not to miss this opportunity to get approval to start the public review.  If the response can't be finished by the January Executive call, the public review would probably have to be pushed beyond the end of February.  So if you can plan to make some time to start looking at the response and revisions in the near future that would be great.  I hope to finish revising the RDF examples tonight, so I may be able to say that the revisions are "done" by tomorrow. 

Steve

**Comment by baskaufs** [comment]
I have completed all of the revisions that I think are necessary in response to the suggestions of the expert reviewers and the review manager.  In going through the marginal comments on the Vocabulary Maintenance Specification Word document, I noticed that the Review Manager raised an issue that came up in the informal discussion at the annual meeting in Costa Rica.  That issue was whether it was always necessary to charter a new maintaining Interest Group when a vocabulary was ratified, or whether the vocabulary could be maintained by an existing Maintenance Interest Group.  I revised Section 2.1 in an attempt to resolve this issue.  You can read the new text in the specification itself or in the change log document.

If you have any feedback on the document, please let me know as soon as possible.  If feedback is given that requires changes, I will try to revise the document as necessary.  If there are no suggestions of changes between now and the scheduled time for the Executive call, I'll take that as the agreement of the Task Group with the changes I made.  If the Review Manager agrees that the response to the reviewers is sufficient, I'll make the final changes to the dates on the documents, publish a release, and the Review Manager can request permission to begin public comment.

**Comment by dagendresen** [comment]
Many thanks for presenting the response to the expert review on time. However, it is also important that you get enough time to complete the revision. If any member of the VOCAB task group need more time to assess the revision, please let Steve or me know. Or simply post a comment here.
I believe that the TDWG executive committee plan their next online conference call around 24-25 January. This means that the Executive will anyway have a very short time to assess the VOCAB revision before the committee meeting.
I hope to be ready with reading through the submitted revision by tomorrow.

https://github.com/tdwg/vocab/blob/master/expert-review-materials/response.md

**Comment by baskaufs** [comment]
No longer relevant post ratification
