### ISSUE TITLE
RFC 2119 notation text

### ISSUE THREAD

**Issue by dagendresen** [tdwg/vocab#48]
The Standards Documentation Specification (SDS) include the recommended RFC-2119-phrase in a chapter named "**1.2 Key words**". The reader might expect a chapter named "Key words" to include important words that are useful to understand the VOCAB standard, and the RFC 2119 keywords are not themselves such key words. I have explored some other technical documents to see how they include the RFC-2119-text. Many technical documents include the RFC-2119-phrase after the abstract and not inside any chapter. Some of the IETF RFC documents include this RFC-2119-phrase in a chapter named "Terminology". Here are some other examples of chapter names I found: "Requirements language" -- "RFC 2119 key words" -- "Notational conventions" -- "Notation" -- "Requirements" -- "Terminology" -- "Terminology and notation". The RFC-2119-phrase might perhaps be included in the "1.5 Definitions" chapter of the SDS?

In chapter 1.2 the RFC-2119-words as referred to as "_key words_", while in chapter 3.2.5 these words are referred to as "_keywords_". RFC 2119 itself refers to these words as "key words". Choosing the spelling "key words" throughout (as is used in RFC 2119) might be preferred?

In chapter 3.2.5 there is also one instance of the spelling "RFC2119" (with space missing).

**Comment by baskaufs** [comment]
In general point 1 of https://github.com/tdwg/ac/issues/258, @Archilegt points out the most recent wording based on <https://www.rfc-editor.org/info/bcp14>. We should just replace current text in all existing documents to follow this recommendation.
