### ISSUE TITLE
SKOS and other demands of descriptors with unique values

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/vocab#49]
@baskaufs  suggested in a [blog](http://baskauf.blogspot.com/2017/03/controlled-values-again.html) the use of SKOS for describing controlled vocabularies. Whether in SKOS or not,  should values (e.g. skos:prefLabel) and perhaps other terms required to be unique in English (or other languages with variants) be in American or British English where they differ? Should TDWG take a position? Should it be up to the author? Is my question irrelevant? Do issues get raised if both may be in play in the same vocabulary description.

Apologies if this issue is already treated in the TDWG proposal

**Comment by baskaufs** [comment]
It is now (2023) a current TDWG practice to use skos:prefLabel with the same label as rdfs:label when serializing term metadata as RDF. They are unique within a vocabulary. No position has been taken on whether to use American or British English. However, I think usage is generally kept consistent within a vocabulary.
