### ISSUE TITLE
Should the normative document be RDF, human-readable, or either?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/vocab#5]
The normative Darwin Core vocabulary document is in RDF.  The normative Audubon Core vocabulary document is in human-readible text (i.e. no particular representation).  Should there be a TDWG-wide policy on the representation of normative vocabulary documents, or should it be the choice of the authors of the vocabulary?

**Comment by ramorrismorris** [comment]
It's probably important to distinguish normative  documents from (possibly several) normative serialization syntaxes, which may be part of them.  FWIW, at a glance it looks like this distinction is made in W3C Recommendations, all (?) of which are human readable with sections specifying syntax of various appropriate kinds. I favour this, and therefor suggest that the question becomes what, if any, guidelines or requirements should there be on RDF syntax specifications of vocabulary documents, and under what circumstances should such specifications be required.

**Comment by xjsachs** [comment]
I support having the normative description of vocabularies in a human-readable format (as per https://docs.google.com/document/d/1GEDlVAHpvFj4RuiwATSy5oIxz5JpgBC84yDyGrZvEB0/edit). I agree with Bob that it may, at times, be appropriate to specify normative serialization syntaxes.

**Comment by tcatapano** [comment]
I also agree with having human-readable normative documentation allowing for multiple syntaxes. In the domain of text encoding, this is basically the approach taken by JATS/ANSI/NISO Z39.96-2012 and the Text Encoding Initiative Guidelines. In these cases the standard is defined by the description of XML elements and attributes implemented in several _non_-normative schemas.

**Comment by baskaufs** [comment]
The general consensus at the 2015-07-15 task group meeting was that normative parts of standards should generally be in human-readable form, although there are cases where it may be appropriate for all or part of machine-readable documents to be labeled as normative.
