### ISSUE TITLE
Two dead resource links

### ISSUE THREAD

**Issue by rowan-ardc** [tdwg/vocab#53]
A pdf version of 1. is available at http://www.gbif.jp/v2/pdf/gbif_kos_whitepaper_v1.pdf

1. [GBIF-KOS] http://www.gbif.org/resource/80656 Recommendations for the Use of Knowledge Organisation Systems by GBIF. 04 Feb 2011. Global Biodiversity Information Facility, 49 pp.

2. [PROCESS] http://www.tdwg.org/about-tdwg/process/ The Standards Development Process. Biodiversity Information Standards.

**Comment by baskaufs** [comment]
Thanks @rowan-ardc I believe I've fixed the broken links.
